project_id = "covuqegxbfjbyclivick"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.analyze-cv]
verify_jwt = false
